services:
backend-services:
    container-name: backend-container
    build:
        context: .
        dockerfile: docker/laravel/Dockerfile
    working_dir: /var/www/app_container
    ports:
        - "8000:8000"
    volumes:
        - ./backend-app:/var/www/app_container
frontend-services:
    container-name: frontend-container
    build:
        context: .
        dockerfile: docker/vuejs/Dockerfile
    working_dir: /app_container
    ports:
        - "5173:5173"
    volumes:
        - ./frontend-app:/app_container

